#!/bin/sh /etc/rc.common
# Detect AN7581 GDM4 RX stuck-at-zero (USXGMII bringup intermittent bug)
# and reboot to retry. See /usr/libexec/lan2-rxwatchdog.

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/libexec/lan2-rxwatchdog
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
