#!/bin/sh /etc/rc.common

USE_PROCD=1
START=96
STOP=10

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/npu-reboot-guard.sh
	procd_set_param env THRESHOLD=1000 REBOOT_HOUR=03
	procd_set_param respawn
	procd_close_instance
}
